version: '3.1'

services:
  storage:
    container_name: storage
    image: postgres:15
    restart: always
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_SERVER_MODE}"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  web:
    build: ./webapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./webapi:/usr/src/app
    ports:
      - 8004:8000
    environment:
      ENVIRONMENT: dev
      TESTING: 0
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@storage:5432/test_storage"
    depends_on:
      - storage
